# Generated by Django 6.0.1 on 2026-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345, max_length=255),
            preserve_default=False,
        ),
    ]
