# Generated by Django 6.0.1 on 2026-02-09 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visibility', models.BooleanField(default=True)),
                ('available_units', models.PositiveIntegerField()),
            ],
        ),
    ]
